global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Scrape configs only contain one scrape target
scrape_configs:
  - job_name: 'my-app'
    scrape_interval: 5s
    static_configs:
      - targets: [host.docker.internal:5000]

  - job_name: 'fastapi-metrics'
    static_configs:
      - targets: [fastapi:5000]

# extra: include rules for alerting
rule_files:
  - rules.yml
